### ISSUE TITLE
文件列表

### ISSUE THREAD

**Issue by Cdreamfly** [rawchen/sims#1]
HTTP状态 500 - 内部服务器错误
类型 异常报告

消息 Cannot read the array length because "<local6>" is null

描述 服务器遇到一个意外的情况，阻止它完成请求。

例外情况

java.lang.NullPointerException: Cannot read the array length because "<local6>" is null
	web.servlet.file.FileListServlet.doPost(FileListServlet.java:28)
	web.servlet.file.FileListServlet.doGet(FileListServlet.java:56)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

**Comment by yoyling** [comment]
> HTTP状态 500 - 内部服务器错误
> 类型 异常报告
> 
> 消息 Cannot read the array length because "" is null
> 
> 描述 服务器遇到一个意外的情况，阻止它完成请求。
> 
> 例外情况
> 
> java.lang.NullPointerException: Cannot read the array length because "" is null
> web.servlet.file.FileListServlet.doPost(FileListServlet.java:28)
> web.servlet.file.FileListServlet.doGet(FileListServlet.java:56)
> javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
> javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
> org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

qq2221999792远程 帮你看看啥问题

**Comment by yoyling** [comment]
> HTTP状态 500 - 内部服务器错误
> 类型 异常报告
> 
> 消息 Cannot read the array length because "" is null
> 
> 描述 服务器遇到一个意外的情况，阻止它完成请求。
> 
> 例外情况
> 
> java.lang.NullPointerException: Cannot read the array length because "" is null
> web.servlet.file.FileListServlet.doPost(FileListServlet.java:28)
> web.servlet.file.FileListServlet.doGet(FileListServlet.java:56)
> javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
> javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
> org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

qq2221999792远程 帮你看看啥问题

**Comment by Cdreamfly** [comment]
怎麽远程？
